// Fetches the "Kuvaas prisliste" Google Sheet (published as CSV) and
// regenerates the price-cat blocks in priser.html between the
// PRICES:START/PRICES:END markers. Sheet columns: Kategori, Behandling,
// Pris (kr), Fra. Category display order follows the sheet's own row
// order (first-seen order), not alphabetical -- lets Arsalan/staff
// reorder categories just by reordering sheet rows.
//
// Run manually: node scripts/update-priser.js
// Run by CI: .github/workflows/update-priser.yml (nightly cron + workflow_dispatch)

import { readFileSync, writeFileSync } from 'node:fs'

const CSV_URL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTlYRE2tM6MJDSe7c7xxSFDBBknrAKhqocN0V9i2hgq8j2mW8md1rLyBPVGpxCvnPJRnULEkRY7w8bJ/pub?gid=0&single=true&output=csv'
const PRISER_HTML = new URL('../priser.html', import.meta.url)
const START_MARKER = '<!-- PRICES:START -- generated by scripts/update-priser.js from the Kuvaas prisliste Google Sheet, do not hand-edit rows here (edit the sheet instead) -->'
const END_MARKER = '<!-- PRICES:END -->'

// Minimal RFC4180 CSV parser -- handles quoted fields (incl. embedded
// commas and "" as an escaped quote), which Google's CSV export uses for
// any Behandling/Kategori text containing a comma (e.g. "Krone, bro &
// protese"). No external dependency for one script this small.
function parseCsv(text) {
  const rows = []
  let row = []
  let field = ''
  let inQuotes = false

  for (let i = 0; i < text.length; i++) {
    const c = text[i]
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++ }
        else inQuotes = false
      } else field += c
    } else if (c === '"') {
      inQuotes = true
    } else if (c === ',') {
      row.push(field); field = ''
    } else if (c === '\r') {
      // ignore, \n handles the line break
    } else if (c === '\n') {
      row.push(field); field = ''
      rows.push(row); row = []
    } else {
      field += c
    }
  }
  if (field.length || row.length) { row.push(field); rows.push(row) }
  return rows.filter(r => r.some(cell => cell.trim() !== ''))
}

function escapeHtml(s) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

// "18720" -> "18.720" -- this site's own existing convention uses a
// period as the thousands separator (not the space toLocaleString('nb-NO')
// would produce, which is the stricter official Norwegian standard but
// doesn't match what priser.html already used before this script existed).
function formatAmount(n) {
  return String(n).replace(/\B(?=(\d{3})+(?!\d))/g, '.')
}

function buildPriceCatBlock(kategori, rows) {
  const items = rows.map(({ behandling, belop, fra }) => {
    const prefix = fra ? 'fra ' : ''
    return `      <div class="price-row"><span>${escapeHtml(behandling)}</span><strong>${prefix}kr ${formatAmount(belop)},-</strong></div>`
  }).join('\n')
  return `  <div class="price-cat reveal">\n    <h3>${escapeHtml(kategori)}</h3>\n    <div class="price-list">\n${items}\n    </div>\n  </div>`
}

async function main() {
  const csv = await fetch(CSV_URL).then(r => {
    if (!r.ok) throw new Error(`CSV fetch failed: ${r.status} ${r.statusText}`)
    return r.text()
  })

  const [header, ...dataRows] = parseCsv(csv)
  const col = name => header.indexOf(name)
  const iKategori = col('Kategori'), iBehandling = col('Behandling'), iPris = col('Pris (kr)'), iFra = col('Fra')
  if ([iKategori, iBehandling, iPris, iFra].includes(-1)) {
    throw new Error(`Sheet header mismatch -- expected "Kategori,Behandling,Pris (kr),Fra", got "${header.join(',')}"`)
  }

  // Group by Kategori in first-seen order (a Map preserves insertion
  // order of its keys), not alphabetically -- so category order in the
  // sheet controls category order on the page.
  const byCategory = new Map()
  for (const r of dataRows) {
    const kategori = r[iKategori].trim()
    const behandling = r[iBehandling].trim()
    const belop = parseInt(r[iPris].trim(), 10)
    const fra = r[iFra].trim().toLowerCase() === 'ja'
    if (!kategori || !behandling || Number.isNaN(belop)) {
      console.warn(`Skipping malformed row: ${JSON.stringify(r)}`)
      continue
    }
    if (!byCategory.has(kategori)) byCategory.set(kategori, [])
    byCategory.get(kategori).push({ behandling, belop, fra })
  }
  if (byCategory.size === 0) throw new Error('No valid price rows parsed from the sheet -- refusing to overwrite priser.html with an empty price list')

  const generated = [...byCategory.entries()]
    .map(([kategori, rows]) => buildPriceCatBlock(kategori, rows))
    .join('\n\n')

  const html = readFileSync(PRISER_HTML, 'utf8')
  const startIdx = html.indexOf(START_MARKER)
  const endIdx = html.indexOf(END_MARKER)
  if (startIdx === -1 || endIdx === -1) throw new Error('PRICES:START/PRICES:END markers not found in priser.html')

  const before = html.slice(0, startIdx + START_MARKER.length)
  const after = html.slice(endIdx)
  const updated = `${before}\n${generated}\n  ${after}`

  writeFileSync(PRISER_HTML, updated)
  console.log(`Wrote ${dataRows.length} price rows across ${byCategory.size} categories to priser.html`)
}

main().catch(err => {
  console.error(err.message)
  process.exit(1)
})
