// Fetches the "Kuvaas prisliste" Google Sheet (published as CSV) and
// regenerates two things from it:
// 1. The full price-cat blocks in priser.html.
// 2. A 3-item teaser (FEATURED_TREATMENTS below) in index.html's
//    "Forutsigbare priser" section -- these were originally hand-copied
//    from priser.html and silently went stale on any price change until
//    Ricky caught the mismatch risk.
// Both are regenerated between each file's own PRICES:START/PRICES:END
// markers. Sheet columns: Kategori, Behandling, Pris (kr), Fra. Category
// display order in priser.html follows the sheet's own row order
// (first-seen order), not alphabetical -- lets Arsalan/staff reorder
// categories just by reordering sheet rows.
//
// Run manually: node scripts/update-priser.js
// Run by CI: .github/workflows/update-priser.yml (nightly cron + workflow_dispatch)

import { readFileSync, writeFileSync } from 'node:fs'

const CSV_URL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTlYRE2tM6MJDSe7c7xxSFDBBknrAKhqocN0V9i2hgq8j2mW8md1rLyBPVGpxCvnPJRnULEkRY7w8bJ/pub?gid=0&single=true&output=csv'
const PRISER_HTML = new URL('../priser.html', import.meta.url)
const INDEX_HTML = new URL('../index.html', import.meta.url)
const END_MARKER = '<!-- PRICES:END -->'
const PRISER_START_MARKER = '<!-- PRICES:START -- generated by scripts/update-priser.js from the Kuvaas prisliste Google Sheet, do not hand-edit rows here (edit the sheet instead) -->'
const INDEX_START_MARKER = '<!-- PRICES:START -- generated by scripts/update-priser.js from the Kuvaas prisliste Google Sheet (FEATURED_TREATMENTS), do not hand-edit rows here (edit the sheet instead) -->'

// The homepage teaser only has room for a handful of rows -- these 3
// (cheap/routine, mid-range, and a bigger procedure) were the original
// hand-picked selection, matched here by exact Behandling text. If one of
// these is ever renamed or removed in the sheet, main() below fails loudly
// rather than silently shipping a shrunk or stale teaser.
const FEATURED_TREATMENTS = [
  'Undersøkelse inkl. 2 bilder og enkel tannstensrens/puss',
  'Tannfarget fylling, 1 flate',
  'Rotfylling, 1 kanal',
]

// Minimal RFC4180 CSV parser -- handles quoted fields (incl. embedded
// commas and "" as an escaped quote), which Google's CSV export uses for
// any Behandling/Kategori text containing a comma (e.g. "Krone, bro &
// protese"). No external dependency for one script this small.
function parseCsv(text) {
  const rows = []
  let row = []
  let field = ''
  let inQuotes = false

  for (let i = 0; i < text.length; i++) {
    const c = text[i]
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++ }
        else inQuotes = false
      } else field += c
    } else if (c === '"') {
      inQuotes = true
    } else if (c === ',') {
      row.push(field); field = ''
    } else if (c === '\r') {
      // ignore, \n handles the line break
    } else if (c === '\n') {
      row.push(field); field = ''
      rows.push(row); row = []
    } else {
      field += c
    }
  }
  if (field.length || row.length) { row.push(field); rows.push(row) }
  return rows.filter(r => r.some(cell => cell.trim() !== ''))
}

function escapeHtml(s) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

// "18720" -> "18.720" -- this site's own existing convention uses a
// period as the thousands separator (not the space toLocaleString('nb-NO')
// would produce, which is the stricter official Norwegian standard but
// doesn't match what priser.html already used before this script existed).
function formatAmount(n) {
  return String(n).replace(/\B(?=(\d{3})+(?!\d))/g, '.')
}

function priceRowSpan({ behandling, belop, fra }) {
  const prefix = fra ? 'fra ' : ''
  return `<span>${escapeHtml(behandling)}</span><strong>${prefix}kr ${formatAmount(belop)},-</strong>`
}

function buildPriceCatBlock(kategori, rows) {
  const items = rows.map(row => `      <div class="price-row">${priceRowSpan(row)}</div>`).join('\n')
  return `  <div class="price-cat reveal">\n    <h3>${escapeHtml(kategori)}</h3>\n    <div class="price-list">\n${items}\n    </div>\n  </div>`
}

// Same staggered-reveal delay index.html's own hand-written version used
// (0s, .06s, .12s, ...) -- kept here so any future change to
// FEATURED_TREATMENTS' length still staggers correctly.
function buildFeaturedTeaser(byBehandling) {
  return FEATURED_TREATMENTS.map((name, i) => {
    const row = byBehandling.get(name)
    if (!row) throw new Error(`FEATURED_TREATMENTS entry "${name}" not found in the sheet -- it was likely renamed or removed. Update FEATURED_TREATMENTS in scripts/update-priser.js to match.`)
    const style = i === 0 ? '' : ` style="transition-delay:.${String(i * 6).padStart(2, '0')}s"`
    return `    <div class="price-row reveal"${style}>${priceRowSpan(row)}</div>`
  }).join('\n')
}

// Replaces everything between startMarker and END_MARKER (both kept
// as-is) with freshly generated content. Shared by priser.html's full
// price list (2-space indent before END_MARKER) and index.html's featured
// teaser (nested one level deeper inside .price-teaser-grid, 4-space).
function updateMarkedSection(fileUrl, startMarker, generated, endIndent) {
  const html = readFileSync(fileUrl, 'utf8')
  const startIdx = html.indexOf(startMarker)
  const endIdx = html.indexOf(END_MARKER)
  if (startIdx === -1 || endIdx === -1) throw new Error(`PRICES:START/PRICES:END markers not found in ${fileUrl}`)

  const before = html.slice(0, startIdx + startMarker.length)
  const after = html.slice(endIdx)
  writeFileSync(fileUrl, `${before}\n${generated}\n${endIndent}${after}`)
}

async function main() {
  const csv = await fetch(CSV_URL).then(r => {
    if (!r.ok) throw new Error(`CSV fetch failed: ${r.status} ${r.statusText}`)
    return r.text()
  })

  const [header, ...dataRows] = parseCsv(csv)
  const col = name => header.indexOf(name)
  const iKategori = col('Kategori'), iBehandling = col('Behandling'), iPris = col('Pris (kr)'), iFra = col('Fra')
  if ([iKategori, iBehandling, iPris, iFra].includes(-1)) {
    throw new Error(`Sheet header mismatch -- expected "Kategori,Behandling,Pris (kr),Fra", got "${header.join(',')}"`)
  }

  // Group by Kategori in first-seen order (a Map preserves insertion
  // order of its keys), not alphabetically -- so category order in the
  // sheet controls category order on the page. byBehandling is a flat
  // index of the same rows, keyed by exact treatment name, feeding
  // index.html's featured teaser below.
  const byCategory = new Map()
  const byBehandling = new Map()
  for (const r of dataRows) {
    const kategori = r[iKategori].trim()
    const behandling = r[iBehandling].trim()
    // Whole-string digit match (not parseInt, which would silently accept
    // "-500" or "5555abc" by parsing only its leading numeric part) --
    // a price must be nothing but digits, and must be positive. Both
    // matter for a dental clinic's own prices: a stray minus sign or typo
    // reaching the live site as "kr -500,-" would be a real embarrassment,
    // not just a cosmetic bug (this exact scenario was caught live before
    // this check existed).
    const priceRaw = r[iPris].trim()
    const belop = /^\d+$/.test(priceRaw) ? parseInt(priceRaw, 10) : NaN
    const fra = r[iFra].trim().toLowerCase() === 'ja'
    if (!kategori || !behandling || Number.isNaN(belop) || belop <= 0) {
      console.warn(`Skipping malformed row: ${JSON.stringify(r)}`)
      continue
    }
    const row = { behandling, belop, fra }
    if (!byCategory.has(kategori)) byCategory.set(kategori, [])
    byCategory.get(kategori).push(row)
    byBehandling.set(behandling, row)
  }
  if (byCategory.size === 0) throw new Error('No valid price rows parsed from the sheet -- refusing to overwrite priser.html with an empty price list')

  const priserGenerated = [...byCategory.entries()]
    .map(([kategori, rows]) => buildPriceCatBlock(kategori, rows))
    .join('\n\n')
  updateMarkedSection(PRISER_HTML, PRISER_START_MARKER, priserGenerated, '  ')
  console.log(`Wrote ${dataRows.length} price rows across ${byCategory.size} categories to priser.html`)

  const teaserGenerated = buildFeaturedTeaser(byBehandling)
  updateMarkedSection(INDEX_HTML, INDEX_START_MARKER, teaserGenerated, '    ')
  console.log(`Wrote ${FEATURED_TREATMENTS.length} featured rows to index.html`)
}

main().catch(err => {
  console.error(err.message)
  process.exit(1)
})
